name: Java CI with Checkstyle

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle Build
        run: gradle compileJava compileTestJava

      - name: Run Checkstyles
        run: gradle clean checkstyleMain

#       - name: Checkstyle Reviewdog
#         uses: reviewdog/action-checkstyle@v1
#         with:
#           github_token: ${{ secrets.MY_TOKEN }}
#           reporter: github-pr-review
